In [16]:
import pandas as pd
import numpy as np
from sklearn import pipeline,preprocessing,metrics,model_selection,ensemble
from sklearn_pandas import DataFrameMapper

In [17]:
data = pd.read_csv('mpg_data_example.csv')
data.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  modelyear  \
0  18.0          8         307.0       130.0    3504          12.0         70   
1  15.0          8         350.0       165.0    3693          11.5         70   
2  18.0          8         318.0       150.0    3436          11.0         70   
3  16.0          8         304.0       150.0    3433          12.0         70   
4  17.0          8         302.0       140.0    3449          10.5         70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [9]:
data[['cylinders','displacement','weight','acceleration','modelyear']]


cylinders  displacement  weight  acceleration  modelyear
0            8         307.0    3504          12.0         70
1            8         350.0    3693          11.5         70
2            8         318.0    3436          11.0         70
3            8         304.0    3433          12.0         70
4            8         302.0    3449          10.5         70
..         ...           ...     ...           ...        ...
393          4         140.0    2790          15.6         82
394          4          97.0    2130          24.6         82
395          4         135.0    2295          11.6         82
396          4         120.0    2625          18.6         82
397          4         119.0    2720          19.4         82

[398 rows x 5 columns]

In [18]:
data.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
modelyear       0
origin          0
car name        0
dtype: int64

In [19]:
from sklearn.impute import SimpleImputer
mapper = DataFrameMapper([
                        (['cylinders','displacement','weight','acceleration','modelyear'], preprocessing.StandardScaler()),
                        (['horsepower'],SimpleImputer()),
                        (['origin'], preprocessing.OneHotEncoder())
                        ])

In [ ]:
data.columns

In [20]:
X=['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'modelyear', 'origin']
Y=['mpg']

In [ ]:
mapper

In [ ]:
data[X]

In [ ]:
data[X].shape

In [116]:
data[Y]

mpg
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
..    ...
393  27.0
394  44.0
395  32.0
396  28.0
397  31.0

[398 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data[X], data[Y], test_size= 0.3)

In [ ]:
data[X]

In [ ]:
X_train.shape

In [ ]:
y_train

In [21]:
print("model 1")
pipeline_obj = pipeline.Pipeline([
    ('mapper',mapper),
    ("model", ensemble.RandomForestRegressor())
])

model 1


In [ ]:
pipeline_obj

In [22]:
pipeline_obj.fit(data[X],data[Y])

/home/surename/Documents/jango/ipynb/.env/lib/python3.7/site-packages/sklearn/pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)


Pipeline(steps=[('mapper',
                 DataFrameMapper(features=[(['cylinders', 'displacement',
                                             'weight', 'acceleration',
                                             'modelyear'],
                                            StandardScaler()),
                                           (['horsepower'], SimpleImputer()),
                                           (['origin'], OneHotEncoder())])),
                ('model', RandomForestRegressor())])

In [23]:
pipeline_obj.predict(data[X])

array([17.005, 14.94 , 17.1  , 16.31 , 17.05 , 14.5  , 13.86 , 14.11 ,
       13.31 , 14.78 , 14.96 , 14.53 , 15.16 , 14.18 , 24.17 , 21.67 ,
       19.487, 21.282, 26.96 , 26.785, 24.32 , 24.12 , 24.92 , 25.39 ,
       21.06 , 10.54 , 10.85 , 11.63 ,  9.83 , 26.99 , 26.166, 25.09 ,
       25.87 , 19.592, 16.985, 17.49 , 18.604, 18.101, 13.91 , 13.59 ,
       14.115, 14.22 , 12.24 , 12.94 , 12.69 , 18.36 , 22.095, 18.68 ,
       18.224, 23.73 , 26.92 , 29.32 , 28.88 , 31.66 , 33.61 , 27.845,
       27.005, 24.302, 25.83 , 23.72 , 20.55 , 22.52 , 13.33 , 13.62 ,
       14.56 , 14.085, 15.87 , 11.7  , 12.85 , 12.44 , 12.98 , 20.62 ,
       14.78 , 13.65 , 13.545, 14.11 , 18.962, 22.736, 20.799, 26.26 ,
       22.315, 26.36 , 22.747, 27.1  , 26.455, 13.195, 14.64 , 13.37 ,
       14.035, 14.58 , 12.   , 13.1  , 13.21 , 14.04 , 12.57 , 12.2  ,
       13.375, 18.443, 16.607, 18.33 , 18.486, 21.9  , 26.32 , 11.53 ,
       12.18 , 12.89 , 12.21 , 18.627, 21.4  , 21.52 , 23.1  , 21.384,
      

# convert to naive bayes model 

In [58]:
from sklearn.naive_bayes import GaussianNB
Gnaive = GaussianNB()

In [26]:
scaler = preprocessing.StandardScaler()
f1 = scaler.fit_transform(data[['cylinders','displacement','weight','acceleration','modelyear']])

In [37]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse=False)

f2 = enc.fit_transform(data[['origin']])

In [42]:
imut = SimpleImputer(missing_values=np.nan, strategy='mean')
f3 = imut.fit_transform(data[['horsepower']])

In [114]:
#f1,f2,f3,label
f3

array([[130.        ],
       [165.        ],
       [150.        ],
       [150.        ],
       [140.        ],
       [198.        ],
       [220.        ],
       [215.        ],
       [225.        ],
       [190.        ],
       [170.        ],
       [160.        ],
       [150.        ],
       [225.        ],
       [ 95.        ],
       [ 95.        ],
       [ 97.        ],
       [ 85.        ],
       [ 88.        ],
       [ 46.        ],
       [ 87.        ],
       [ 90.        ],
       [ 95.        ],
       [113.        ],
       [ 90.        ],
       [215.        ],
       [200.        ],
       [210.        ],
       [193.        ],
       [ 88.        ],
       [ 90.        ],
       [ 95.        ],
       [104.46938776],
       [100.        ],
       [105.        ],
       [100.        ],
       [ 88.        ],
       [100.        ],
       [165.        ],
       [175.        ],
       [153.        ],
       [150.        ],
       [180.        ],
       [170

In [135]:
#label = np.array(data['mpg'])
#label = data.mpg
lebel = le.fit_transform(data['mpg'])
lebel

array([ 17,   7,  17,   9,  13,   7,   5,   5,   5,   7,   7,   5,   7,
         5,  49,  38,  17,  34,  63,  58,  53,  49,  53,  58,  34,   1,
         1,   2,   0,  63,  68,  53,  53,  22,   9,  13,  22,  17,   5,
         5,   5,   5,   3,   4,   4,  17,  38,  22,  17,  42,  68,  76,
        76,  80, 105,  63,  58,  49,  53,  42,  28,  34,   4,   5,   7,
         5,  13,   2,   4,   3,   4,  22,   7,   4,   4,   5,  17,  38,
        34,  58,  38,  68,  42,  68,  63,   4,   5,   4,   5,   7,   3,
         4,   4,   5,   4,   3,   4,  17,   9,  17,  17,  42,  58,   2,
         3,   4,   3,  17,  28,  34,  38,  17,  22,  34,  58,   7,   9,
        72,  49,  28,  22,   7,  49,  28,   2,  28,  34,  22,   7,  80,
        58,  86,  53,   9,   9,  17,   9,   4,   5,   5,   5,  72,  58,
        58,  80,  86,  68,  49,  58,  49,  58,  80,  22,  17,   7,   7,
         9,   7,   9,   5,  13,   9,   7,  17,  34,  28,   4,  72,  42,
        28,  42,  49,  53,  49,  17,  72,  22,  42,  42,  38,  5

In [52]:
feature = data[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'modelyear', 'origin']]
feature

cylinders  displacement  horsepower  weight  acceleration  modelyear  \
0            8         307.0       130.0    3504          12.0         70   
1            8         350.0       165.0    3693          11.5         70   
2            8         318.0       150.0    3436          11.0         70   
3            8         304.0       150.0    3433          12.0         70   
4            8         302.0       140.0    3449          10.5         70   
..         ...           ...         ...     ...           ...        ...   
393          4         140.0        86.0    2790          15.6         82   
394          4          97.0        52.0    2130          24.6         82   
395          4         135.0        84.0    2295          11.6         82   
396          4         120.0        79.0    2625          18.6         82   
397          4         119.0        82.0    2720          19.4         82   

     origin  
0         1  
1         1  
2         1  
3         1  
4         1  
..      ...  
393       1  
394       2  
395       1  
396       1  
397       1  

[398 rows x 7 columns]

In [136]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

column_trans = make_column_transformer(
    (StandardScaler(), ['cylinders','displacement','weight','acceleration','modelyear']),
    (SimpleImputer(missing_values=np.nan, strategy='mean'), ['horsepower']),
    (OneHotEncoder(), ['origin']),
    remainder='passthrough')

In [137]:
features = column_trans.fit_transform(feature)
features

array([[ 1.49819126,  1.0906037 ,  0.63086987, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.49819126,  1.5035143 ,  0.85433297, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.49819126,  1.19623199,  0.55047045, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.85632057, -0.56103873, -0.79858454, ...,  1.        ,
         0.        ,  0.        ],
       [-0.85632057, -0.70507731, -0.40841088, ...,  1.        ,
         0.        ,  0.        ],
       [-0.85632057, -0.71467988, -0.29608816, ...,  1.        ,
         0.        ,  0.        ]])

In [ ]:
tupX = np.array(data[X])
tupX.shape

In [ ]:
from sklearn.model_selection import train_test_split

X_trainin, X_tes, Y_train, Y_tes = train_test_split(tupX, tupY, test_size= 0.3)

In [103]:
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(column_trans, Gnaive)

In [139]:
pipe.fit(feature, lebel)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['cylinders', 'displacement',
                                                   'weight', 'acceleration',
                                                   'modelyear']),
                                                 ('simpleimputer',
                                                  SimpleImputer(),
                                                  ['horsepower']),
                                                 ('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['origin'])])),
                ('gaussiannb', GaussianNB())])

# AKHIRNYA BISA TIDUR BITCH....!!! (Problem SOLVED)




In [140]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, feature, lebel, cv=5, scoring='accuracy').mean()

/home/surename/Documents/jango/ipynb/.env/lib/python3.7/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


0.06009493670886077

In [141]:
print("model 2")

pipeline_obj2 = pipeline.Pipeline([
    ('mapper',column_trans),
    ("model", GaussianNB())
])

model 2


In [142]:
pipeline_obj2.fit(feature, lebel)

Pipeline(steps=[('mapper',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['cylinders', 'displacement',
                                                   'weight', 'acceleration',
                                                   'modelyear']),
                                                 ('simpleimputer',
                                                  SimpleImputer(),
                                                  ['horsepower']),
                                                 ('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['origin'])])),
                ('model', GaussianNB())])

# test

In [117]:
#from sklearn import preprocessing

df = pd.read_csv('datalatihsoalNaivebayes1.csv')
df.head()

Kehadiran     Lingkungan    Kerjasama          Prakarsa Rekomendasi
0     Rajin  Kurang Peduli        Mampu   Tidak Inisiatif       Tidak
1     Cukup         Peduli  Tidak Mampu         Inisiatif          Ya
2     Rajin  Kurang Peduli  Tidak Mampu  Kurang Inisiatif       Tidak
3     Rajin         Peduli        Mampu         Inisiatif          Ya
4     Rajin         Peduli        Mampu         Inisiatif          Ya

In [118]:
le = preprocessing.LabelEncoder()

In [119]:
feature1 = le.fit_transform(df['Kehadiran'])
feature2 = le.fit_transform(df['Lingkungan'])
feature3 = le.fit_transform(df['Kerjasama'])
feature4 = le.fit_transform(df['Prakarsa'])


In [121]:
label = le.fit_transform(df['Rekomendasi'])
features=list(zip(feature1, feature2, feature3, feature4))



In [79]:
Xlatih=list(zip(f1, f2, f3))
Xlatih

[(array([ 1.49819126,  1.0906037 ,  0.63086987, -1.29549834, -1.62742629]),
  array([1., 0., 0.]),
  array([130.])),
 (array([ 1.49819126,  1.5035143 ,  0.85433297, -1.47703779, -1.62742629]),
  array([1., 0., 0.]),
  array([165.])),
 (array([ 1.49819126,  1.19623199,  0.55047045, -1.65857724, -1.62742629]),
  array([1., 0., 0.]),
  array([150.])),
 (array([ 1.49819126,  1.06179598,  0.54692342, -1.29549834, -1.62742629]),
  array([1., 0., 0.]),
  array([150.])),
 (array([ 1.49819126,  1.04259084,  0.56584093, -1.84011669, -1.62742629]),
  array([1., 0., 0.]),
  array([140.])),
 (array([ 1.49819126,  2.26211751,  1.62049216, -2.02165614, -1.62742629]),
  array([1., 0., 0.]),
  array([198.])),
 (array([ 1.49819126,  2.50218182,  1.63586264, -2.38473503, -1.62742629]),
  array([1., 0., 0.]),
  array([220.])),
 (array([ 1.49819126,  2.36774581,  1.58620417, -2.56627448, -1.62742629]),
  array([1., 0., 0.]),
  array([215.])),
 (array([ 1.49819126,  2.51178439,  1.71980909, -2.02165614, -1.

In [122]:
features

[(2, 0, 0, 2),
 (0, 1, 1, 0),
 (2, 0, 1, 1),
 (2, 1, 0, 0),
 (2, 1, 0, 0),
 (0, 1, 1, 0),
 (1, 1, 1, 1),
 (2, 1, 1, 1),
 (2, 1, 0, 0),
 (1, 0, 1, 1),
 (0, 1, 0, 1),
 (2, 1, 0, 2),
 (0, 1, 0, 0),
 (2, 1, 0, 0)]

In [123]:
label

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1])

In [ ]:
X_trainin

In [ ]:
x_train

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(features, label, test_size=0.3)

In [138]:
classifier = GaussianNB()
classifier.fit(features,lebel)



GaussianNB()

In [ ]:
accuracy = classifier.score(x_test, y_test)
print(accuracy)